apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongodb
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: localhost:27017
    - name: databaseName
      value: Product-Catalog
    - name: collectionName
      value: Products